export const CATEGORIES = [
    { id: 'jewelry', name: 'Jewelry & Accessories' },
    { id: 'clothing', name: 'Clothing & Apparel' },
    { id: 'home', name: 'Home & Living' },
    { id: 'art', name: 'Art & Collectibles' },
    { id: 'craft-supplies', name: 'Craft Supplies' },
    { id: 'gifts', name: 'Gifts & Gift Cards' },
    { id: 'weddings', name: 'Weddings & Celebrations' },
    { id: 'toys', name: 'Toys & Games' },
  ];
  
  export const MATERIALS = [
    'Wood',
    'Metal',
    'Ceramic',
    'Glass',
    'Fabric',
    'Leather',
    'Paper',
    'Clay',
    'Stone',
    'Yarn',
    'Mixed Media',
    'Other',
  ];

  export const FEATURED_CREATORS = [
    {
      id: '1',
      name: 'Ankita Pal',
      avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=600',
      specialty: 'Ceramic Pottery',
      bio: 'Creating handcrafted ceramic pieces inspired by nature and organic forms.',
      location: 'Pune, IND',
    },
    {
      id: '2',
      name: 'Mishita Singh',
      avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=600',
      specialty: 'Woodworking',
      bio: 'Crafting heirloom quality wooden furniture using traditional joinery techniques.',
      location: 'Mumbia, IND',
    },
    {
      id: '3',
      name: 'Shweta Gupta',
      avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=600',
      specialty: 'Jewelry Design',
      bio: 'Handcrafting unique jewelry pieces from ethically sourced materials.',
      location: 'Delhi, IND',
    },
  ];
  
  export const SAMPLE_CRAFTS = [
    {
      id: '1',
      title: 'Handcrafted Ceramic Bowl Set',
      description: 'Set of 4 unique ceramic bowls, perfect for everyday use or special occasions. Each piece is handmade with care and finished with a food-safe glaze.',
      price: 850.00,
      images: ['https://images.pexels.com/photos/4992463/pexels-photo-4992463.jpeg?auto=compress&cs=tinysrgb&w=600'],
      category: 'home',
      creatorId: '1',
      materials: ['Ceramic', 'Clay'],
      featured: true,
    },
    {
      id: '2',
      title: 'Reclaimed Wood Coffee Table',
      description: 'One-of-a-kind coffee table crafted from reclaimed barn wood. Features a smooth finish while preserving the natural character of the wood.',
      price: 325.00,
      images: ['https://images.pexels.com/photos/2092058/pexels-photo-2092058.jpeg?auto=compress&cs=tinysrgb&w=600'],
      category: 'home',
      creatorId: '2',
      materials: ['Wood'],
      featured: true,
    },
    {
      id: '3',
      title: 'Sterling Silver Leaf Earrings',
      description: 'Delicate sterling silver earrings inspired by natural leaf forms. Lightweight and perfect for everyday wear.',
      price: 450.00,
      images: ['https://images.pexels.com/photos/1413420/pexels-photo-1413420.jpeg?auto=compress&cs=tinysrgb&w=600'],
      category: 'jewelry',
      creatorId: '3',
      materials: ['Metal', 'Silver'],
      featured: true,
    },
    {
      id: '4',
      title: 'Hand-Knit Wool Throw Blanket',
      description: 'Luxuriously soft throw blanket hand-knit from 100% merino wool. Perfect for cozy evenings or as a decorative accent.',
      price: 220.00,
      images: ['https://images.pexels.com/photos/6850711/pexels-photo-6850711.jpeg?auto=compress&cs=tinysrgb&w=600'],
      category: 'home',
      creatorId: '3',
      materials: ['Fabric', 'Yarn'],
      featured: false,
    },
    {
      id: '5',
      title: 'Handmade Leather Wallet',
      description: 'Classic bifold wallet handcrafted from vegetable-tanned leather. Will develop a beautiful patina with use.',
      price: 650.00,
      images: ['https://images.pexels.com/photos/2280913/pexels-photo-2280913.jpeg?auto=compress&cs=tinysrgb&w=600'],
      category: 'accessories',
      creatorId: '2',
      materials: ['Leather'],
      featured: true,
    },
    {
      id: '6',
      title: 'Wheel-Thrown Ceramic Planter',
      description: 'Modern ceramic planter wheel-thrown and glazed by hand. Perfect for houseplants and includes drainage hole.',
      price: 480.00,
      images: ['https://images.pexels.com/photos/5706233/pexels-photo-5706233.jpeg?auto=compress&cs=tinysrgb&w=600'],
      category: 'home',
      creatorId: '1',
      materials: ['Ceramic', 'Clay'],
      featured: false,
    },
  ];